name: chrome1
on: workflow_dispatch
jobs:
  test-build:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
    env:
      FOO: bar
    steps:
      - name: Build chromedriver URL
        run: |
          FULL_CHR_VERS=`google-chrome --version | sed -e "s/Google Chrome //" | sed -e "s/ //g"`
          echo $FULL_CHR_VERS
          TRUNC_CHR_VERS=`echo $FULL_CHR_VERS | sed -e 's#\.[0-9]\+$##'`
          echo $TRUNC_CHR_VERS
          CHR_DRIVER_VERS=`curl https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$TRUNC_CHR_VERS`
          echo $CHR_DRIVER_VERS
          echo "chromedriver-url=https://chromedriver.storage.googleapis.com/$CHR_DRIVER_VERS/chromedriver_linux64.zip" >> $GITHUB_ENV
      - name: Use chromedriver URL
        run: |
          wget ${{ env.chromedriver-url }}
          unzip chromedriver_linux64.zip
