name: chrome1
on: workflow_dispatch
jobs:
  test-build:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
    env:
      FOO: bar
    steps:
      - name: step1
        id: stepId1
        run: |
          google-chrome --version
          google-chrome --version | sed -e "s/Google Chrome /ChromeVersion=/" | sed -e "s/ //g" >> $GITHUB_OUTPUT
      - name: step2
        id: stepId2
        run: |
          echo "chromedriver-url=https://chromedriver.storage.googleapis.com/${{ steps.stepId1.outputs.ChromeVersion }}/chromedriver_linux64.zip" >> $GITHUB_OUTPUT
      - name: step3
        id: stepId3
        run: |
          wget ${{ steps.stepId2.outputs.chromedriver-url }}
          unzip chromedriver_linux64.zip
