name: sim-release
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
jobs:
  run-tests:
    uses: ./.github/workflows/sim-testing.yml
    with:
      save-release-artifacts: true
  release:
    needs: run-tests
    environment: publish
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
    steps:
      # Download artifacts from testing job
      - name: Obtain artifacts from testing job
        uses: actions/download-artifact@v3
        with:
          name: sim-artifact
      # Check download
      - name: Check downloaded artifact
        run: |
          ls -l repo
          ls -l repo/a/b
          cat repo/a/b/built_file.js
          ls -l other
          ls -l images
      # -------------------------------------
      # Version number
      # Number from tag
      - name: get version number from tag
        id: get-vers-from-tag
        run: echo "${{github.ref_name}}" | sed 's/v/version=/' >> $GITHUB_OUTPUT
      # Number from file
      - name: check version from package.json
        id: get-vers-from-file
        working-directory: repo/js
        run: |
          echo "version=`grep version package.json | sed -e 's/  "version": "//' | sed -e 's/",//'`" >> $GITHUB_OUTPUT
      # Verify the two numbers are the same
      - name: Check version number
        run: |
          echo "Tag version: ${{steps.get-vers-from-tag.outputs.version}}"
          echo "File version: ${{steps.get-vers-from-file.outputs.version}}"
          test "${{steps.get-vers-from-tag.outputs.version}}" = "${{steps.get-vers-from-file.outputs.version}}"
      # -------------------------------------
      # Publishing
      # Manually control whether we're doing the publishing steps or not
      - name: Switch publishing on or off
        id: switch
        run: echo "pub-npm=no" >> $GITHUB_OUTPUT
      # -------------------------------------
      # npm
      # Check that certain files will be included
      - name: Check npm publish dry-run
        working-directory: repo/js
        run: |
          npm publish --dry-run 2>&1 | grep LICENSE
          npm publish --dry-run 2>&1 | grep NOTICE
      # npm publish
      - if: ${{ steps.switch.outputs.pub-npm == 'yes' }}
        name: Do npm publish
        working-directory: repo/js
        run: |
          echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_PUBLISH_01}}" > ~/.npmrc
          echo "//registry.npmjs.org/:always-auth=true" >> ~/.npmrc
          npm publish
