name: sim-testing
on:
  #pull_request:
  #push:
  #  branches:
  #    - '**'
  #  tags-ignore:
  #    - '**'
  workflow_dispatch:
    inputs:
      save-release-artifacts:
        description: 'Whether to upload artifacts for release processing'
        type: boolean
        default: false
  workflow_call:
    inputs:
      save-release-artifacts:
        description: 'Whether to upload artifacts for release processing'
        type: boolean
        default: false
        required: false
jobs:
  unit-tests:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
    steps:
      # Repo checkout
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: repo
      # Building sth
      - name: Build
        working-directory: repo
        run: |
          mkdir -p a/b
          echo "Build at `date`" >> a/b/built_file.js
      # Making some other stuff
      - name: Make other stuff
        run: |
          mkdir other
          echo "foo" > other/stuff
      # Unit tests
      - name: Run unit tests
        working-directory: repo
        run: grep pass c/foo
      # ---------------------------------------------
      # Docker
      # Make and zip context directory
      - name: Make and zip a context dir
        run: |
          mkdir context
          mkdir contexts
          cp -r repo context
          cp -r other context
          cp repo/c/Dockerfile context
          cd context; tar -czh -f ${{github.workspace}}/contexts/context.tar.gz .
      # Set up buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      # Build image for testing
      - name: Build image for testing
        uses: docker/build-push-action@v4
        with:
          context: context
          tags: wflow01:testing
          load: true
          cache-to: type=gha
          cache-from: type=gha
      # Run, for proof of concept
      - name: Check image contents
        run: docker run --rm wflow01:testing sh -c "ls -l /usr/local/share"
      # ---------------------------------------------
      # Conditional upload of artifacts
      - if: ${{inputs.save-release-artifacts}}
        name: Save release artifacts
        uses: actions/upload-artifact@v3
        with:
          name: sim-artifact
          path: |
            repo
            other
            contexts
