name: sim-release
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
jobs:
  run-tests:
    uses: ./.github/workflows/sim-testing.yml
    with:
      save-release-artifacts: true
  release:
    needs: run-tests
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
    steps:
      - name: Obtain artifacts from testing job
        uses: actions/download-artifact@v3
        with:
          name: sim-artifact
      - name: Check downloaded artifact
        run: |
          ls -l repo
          ls -l repo/a/b
          cat repo/a/b/built_file.js
      - name: get version number
        id: get-vers
        run: echo "${{github.ref_name}}" | sed 's/v/version=/' >> $GITHUB_OUTPUT
      - name: Check version number
        run: echo "${{steps.get-vers.outputs.version}}"
