name: try-pfsc-repo-build-action
on:
  workflow_dispatch:
    inputs:
      content-vers:
        description: "version at which to build pfsc content repo"
        type: string
        default: "WIP"
      container-persist:
        description: "keep container running"
        type: boolean
        default: false
jobs:
  build-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout wt
        uses: actions/checkout@v3
        with:
          path: wt
      - name: Try repo build action
        uses: ./wt/.github/actions/pfsc-repo-build
        with:
          content-repo: "proofscape/docs"
          content-vers: ${{inputs.content-vers}}
          container-persist: ${{inputs.container-persist && 'yes' || 'no'}}
      - if: ${{inputs.container-persist}}
        name: Try to use container
        run: |
          docker exec pise bash -c "ls -l"
